local extra_liners = {
  "head",
  "body",
  "/body",
  "/html",
  "p",
  "section",
  "/section",
  "div",
  "/div",
  "ol",
  "/ol",
  "ul",
  "/ul",
  "li",
  "blockquote",
  "/blockquote",
  "figure",
  "/figure",
  "figcaption",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "hgroup",
  "/hgroup",
  "header",
  "/header",
  "nav",
  "/nav",
  "dt",
  "dd",
}

return {
  cmd = { "vscode-html-language-server", "--stdio" },
  filetypes = {
    "html",
    "xhtml",
  },
  root_markers = { "package.json", ".git" },
  init_options = {
    provideFormatter = true,
    embeddedLanguages = { css = true, javascript = true },
    configurationSection = { "html", "css", "javascript" },
  },
  settings = {
    html = {
      format = {
        wrapLineLength = 0,
        indentInnerHtml = false,
        maxPreserveNewLines = 2,
        extraLiners = table.concat(extra_liners, ", "),
      },
    },
  },
}
